import type { Ticket, TicketCounts } from "./types";

export const ticketCounts: TicketCounts = {
  myTickets: 5,
  groupTickets: 42,
  flagged: 2,
  messages: 5,
};

export const mockTickets: Ticket[] = [
  {
    id: "t-110",
    number: 110,
    isUnread: true,
    isFlagged: false,
    updatedAt: "2025-06-06T04:32:00",
    requestType: "Legal Dept Request",
    requestCategory: "General Inquiry",
    requestDetail: "Title deed verification for Plot 47, Karen — client awaiting clearance letter",
    latestNote: "Forwarded to legal team for review. ETA 2 business days.",
    status: "assigned",
    priority: "high",
    alertLevel: "not_completed",
    assignee: "Grace Mwangi",
    requester: "James Ochieng",
    department: "Sales",
    createdAt: "2025-06-04T09:15:00",
  },
  {
    id: "t-109",
    number: 109,
    isUnread: false,
    isFlagged: true,
    updatedAt: "2025-06-05T14:18:00",
    requestType: "Property Inquiry",
    requestCategory: "Site Visit Request",
    requestDetail: "Client wants to schedule site visit for Ruiru Phase 2 plots this Saturday",
    latestNote: "Site visit confirmed for Sat 10 AM. Transport arranged.",
    status: "approved",
    priority: "medium",
    alertLevel: "on_track",
    assignee: "Peter Kamau",
    requester: "Sarah Wanjiku",
    department: "Sales",
    createdAt: "2025-06-03T11:20:00",
  },
  {
    id: "t-108",
    number: 108,
    isUnread: true,
    isFlagged: false,
    updatedAt: "2025-06-05T10:45:00",
    requestType: "IT Request",
    requestCategory: "Software Support",
    requestDetail: "CRM login issue — unable to access lead pipeline dashboard",
    latestNote: "Password reset sent. Awaiting user confirmation.",
    status: "pending",
    priority: "medium",
    alertLevel: "due_soon",
    assignee: "David Otieno",
    requester: "Mary Njeri",
    department: "Marketing",
    createdAt: "2025-06-05T08:30:00",
  },
  {
    id: "t-107",
    number: 107,
    isUnread: false,
    isFlagged: false,
    updatedAt: "2025-06-04T16:22:00",
    requestType: "Finance Request",
    requestCategory: "Payment Confirmation",
    requestDetail: "Deposit receipt for KES 500,000 — Kitengela Plot 12 needs verification",
    latestNote: null,
    status: "resolved",
    priority: "high",
    alertLevel: "on_track",
    assignee: "Anne Wambui",
    requester: "John Mburu",
    department: "Finance",
    createdAt: "2025-06-02T14:00:00",
  },
  {
    id: "t-106",
    number: 106,
    isUnread: false,
    isFlagged: true,
    updatedAt: "2025-06-04T11:05:00",
    requestType: "Legal Dept Request",
    requestCategory: "Contract Review",
    requestDetail: "Sale agreement amendment for joint ownership — two buyers on one plot",
    latestNote: "Draft amendment sent to client for review and signature.",
    status: "assigned",
    priority: "urgent",
    alertLevel: "overdue",
    assignee: "Grace Mwangi",
    requester: "Peter & Jane Kilonzo",
    department: "Legal",
    createdAt: "2025-05-30T10:00:00",
  },
  {
    id: "t-105",
    number: 105,
    isUnread: false,
    isFlagged: false,
    updatedAt: "2025-06-03T09:40:00",
    requestType: "Property Inquiry",
    requestCategory: "Pricing & Availability",
    requestDetail: "Bulk purchase inquiry — 5 adjacent plots in Athi River commercial zone",
    latestNote: "Pricing sheet and availability map shared via email.",
    status: "resolved",
    priority: "medium",
    alertLevel: "on_track",
    assignee: "Peter Kamau",
    requester: "ABC Holdings Ltd",
    department: "Sales",
    createdAt: "2025-06-01T16:45:00",
  },
  {
    id: "t-104",
    number: 104,
    isUnread: true,
    isFlagged: false,
    updatedAt: "2025-06-03T07:15:00",
    requestType: "Facilities Request",
    requestCategory: "Office Maintenance",
    requestDetail: "Conference room projector not displaying — board meeting at 2 PM today",
    latestNote: "Technician dispatched. Replacement cable en route.",
    status: "assigned",
    priority: "urgent",
    alertLevel: "not_completed",
    assignee: "Facilities Team",
    requester: "HR Department",
    department: "Operations",
    createdAt: "2025-06-03T06:50:00",
  },
  {
    id: "t-103",
    number: 103,
    isUnread: false,
    isFlagged: false,
    updatedAt: "2025-06-02T15:30:00",
    requestType: "IT Request",
    requestCategory: "Hardware",
    requestDetail: "New laptop request for field sales agent — Nyeri region",
    latestNote: "Approved by management. Procurement in progress.",
    status: "approved",
    priority: "low",
    alertLevel: "on_track",
    assignee: "David Otieno",
    requester: "Sales — Nyeri",
    department: "IT",
    createdAt: "2025-05-28T09:00:00",
  },
  {
    id: "t-102",
    number: 102,
    isUnread: false,
    isFlagged: false,
    updatedAt: "2025-06-01T12:00:00",
    requestType: "Property Inquiry",
    requestCategory: "Diaspora Client",
    requestDetail: "UK-based client seeking investment plots with flexible payment plan",
    latestNote: "Video call scheduled for Thursday 4 PM EAT.",
    status: "pending",
    priority: "high",
    alertLevel: "due_soon",
    assignee: "Peter Kamau",
    requester: "Michael Oduor (UK)",
    department: "Sales",
    createdAt: "2025-05-31T18:20:00",
  },
  {
    id: "t-101",
    number: 101,
    isUnread: false,
    isFlagged: false,
    updatedAt: "2025-05-31T17:45:00",
    requestType: "Finance Request",
    requestCategory: "Refund Processing",
    requestDetail: "Client cancelled reservation — refund of KES 150,000 deposit requested",
    latestNote: "Refund approved. Processing within 5–7 business days.",
    status: "resolved",
    priority: "medium",
    alertLevel: "on_track",
    assignee: "Anne Wambui",
    requester: "Lucy Chebet",
    department: "Finance",
    createdAt: "2025-05-29T13:10:00",
  },
  {
    id: "t-100",
    number: 100,
    isUnread: true,
    isFlagged: false,
    updatedAt: "2025-05-30T08:20:00",
    requestType: "Marketing Request",
    requestCategory: "Campaign Assets",
    requestDetail: "Social media graphics needed for Ruiru Phase 2 launch campaign",
    latestNote: "Design brief received. First drafts due Monday.",
    status: "new",
    priority: "medium",
    alertLevel: "not_completed",
    assignee: null,
    requester: "Marketing Team",
    department: "Marketing",
    createdAt: "2025-05-30T08:00:00",
  },
  {
    id: "t-99",
    number: 99,
    isUnread: false,
    isFlagged: false,
    updatedAt: "2025-05-29T11:30:00",
    requestType: "Legal Dept Request",
    requestCategory: "Compliance",
    requestDetail: "Annual regulatory filing documentation for NCA compliance review",
    latestNote: "All documents compiled. Awaiting final sign-off.",
    status: "pending",
    priority: "high",
    alertLevel: "due_soon",
    assignee: "Grace Mwangi",
    requester: "Compliance Office",
    department: "Legal",
    createdAt: "2025-05-25T10:00:00",
  },
];
